
const BASE_URL = "http://192.53.114.191:5000/api";
const USERS_BASE_URL = `${BASE_URL}/users`;
const PRODUCTS_BASE_URL = `${BASE_URL}/products`;
const ORDERS_BASE_URL = `${BASE_URL}/orders`;
const PAYMENTS_BASE_URL =`${BASE_URL}/payments`;
const CATEGORIES_BASE_URL =`${BASE_URL}/categories`;

export {BASE_URL,USERS_BASE_URL,PRODUCTS_BASE_URL,ORDERS_BASE_URL,PAYMENTS_BASE_URL,CATEGORIES_BASE_URL};